add_device_config: /api/sky-nap/device/rawconfig
add_device_config_route: /api/sky-nap/device/route
add_device_credential: /api/sky-nap/device/credential
add_sky_biz_domain: /api/sky-nap/device-group/sky_biz_domain?upperId=sky_idc_id&upperModelKey=sky_idc
add_sky_firewall: /api/sky-nap/task/add-firewall
add_sky_gateway: /api/sky-nap//task/add-gateway
add_sky_idc: /api/sky-nap/device-group/sky_idc?upperId=project_id&upperModelKey=project
add_sky_loadbalancer: /api/sky-nap/task/add-load-balance
add_sky_switch_router: /api/sky-nap/task/add-switch-router
add_topo: /api/sky-nap/topology
add_type: /api/sky-nap/device/type
add_vendor: /api/sky-nap/device/vendor
add_version: /api/sky-nap/device/version
choose_device_config: /api/sky-nap/device/rawconfig/device_id/active/config_id
choose_device_config_route: /api/sky-nap/device/route/device_id/active/route_id
dst:
  host: 192.168.30.51
  password: r00tme
  username: admin
get_cmdb_sky_firewall_id: /api/sky-cmdb/resource/instance/list/sky_firewall?page=0&size=20
get_cmdb_sky_gateway_id: /api/sky-cmdb/resource/instance/list/sky_gateway?page=0&size=20
get_cmdb_sky_loadbalancer_id: /api/sky-cmdb/resource/instance/list/sky_loadbalancer?page=0&size=20
get_cmdb_sky_switch_router_id: /api/sky-cmdb/resource/instance/list/sky_switch_router?page=0&size=20
get_device_config_info: /api/sky-nap/device/rawconfig/config_id
get_device_config_list: /api/sky-nap/device/rawconfig?deviceId=device_id&page=0&size=20
get_device_config_route_info: /api/sky-nap/device/route/config_id
get_device_config_route_list: /api/sky-nap/device/route?deviceId=device_id&page=0&size=20
get_device_credential_list: /api/sky-nap/device/credential?page=0&size=1000
get_device_tree_api: /api/sky-nap/device-group
get_sky_firewall_info: /api/sky-nap/firewall/device_id
get_sky_gateway: /api/sky-nap/gateway/get_sky_gateway_id
get_sky_loadbalancer: /api/sky-nap/load-balance/sky_loadbalancer_id
get_sky_switch_router: /api/sky-nap/switch-router/sky_switch_router_id
get_topo_info: /api/sky-nap/topology/src_topo_id
get_topo_list: /api/sky-nap/topology?page=0
src:
  host: 192.168.30.51
  password: r00tme
  username: admin
type_list_api: /api/sky-nap/device/type?keyword=&page=0&size=1000
vendor_list_api: /api/sky-nap/device/vendor?keyword=&page=0&size=1000
version_list_api: /api/sky-nap/device/version/list?page=0&size=1000
version_template_info: /api/sky-nap/device/version/version_id
write_template_api: /api/sky-nap/device/template/list
